name: Approve PR

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  deploy-1:
    runs-on: ubuntu-latest
    environment: "${{ github.event.inputs.environment }}"
    env:
      ENV: "${{ github.event.inputs.environment }}"
    steps:
      - name: echo
        run: |
          #!/bin/bash
          echo "$ENV"

  deploy-2:
    needs: deploy-1
    runs-on: ubuntu-latest
    env:
      ENV: "${{ github.event.inputs.environment }}"
    steps:
      - name: echo
        run: |
          #!/bin/bash
          echo "$ENV"
