name: Deploy to Staging

# This workflow must be triggered manually after development deployment
on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Confirm deployment to staging'
        required: true
        type: boolean
        default: false

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    # Only run if confirmation is provided
    if: ${{ github.event.inputs.confirm_deploy == 'true' }}
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: myapp:latest
      
      - name: Run container in staging
        run: |
          docker run --rm -e ENVIRONMENT="staging" -e ENV_CONFIG="Performance testing enabled" myapp:latest
      
      - name: Deployment complete message
        run: |
          echo "Staging deployment complete. To proceed to production, manually run the 'Deploy to Production' workflow."
