name: Deploy to Production

# This workflow must be triggered manually after staging deployment
on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Confirm deployment to production'
        required: true
        type: boolean
        default: false

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    # Only run if confirmation is provided
    if: ${{ github.event.inputs.confirm_deploy == 'true' }}
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: myapp:latest
      
      - name: Run container in production
        run: |
          docker run --rm -e ENVIRONMENT="production" -e ENV_CONFIG="High availability mode" myapp:latest
      
      - name: Deployment complete message
        run: |
          echo "Production deployment complete!"
