name: echo
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - run: echo ${{ github.ref }}
