name: echo
on:
  workflow_dispatch:
    inputs:
      branch:
        default: main
        required: true
        type: string
  workflow_call:
    inputs:
      branch:
        default: main
        required: true
        type: string
  pull_request:
    branches:
      - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.branch }}
