name: open-pr
on:
  workflow_dispatch:
  workflow_call:
jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - run: |
          timestamp="$(date +%s)"
          echo "$timestamp" > "$timestamp"
      - uses: peter-evans/create-pull-request@v5
        with:
          branch: auto-pr
  echo:
    uses: ./.github/workflows/echo.yaml@auto-pr
    needs:
      open-pr
